### ISSUE TITLE
SSL Handshake Failed

### ISSUE THREAD

**Issue by myn** [theJayTea/WritingTools#26]
Getting this error upon triggering a query:

![image](https://github.com/user-attachments/assets/15d60dd0-b07b-42ec-a4d9-a57f59b069c5)

I am on a Windows 11 Laptop that goes through a corporate firewall.   No issues hitting [
https://generativelanguage.googleapis.com/](https://generativelanguage.googleapis.com/) through the web browser.

**Comment by theJayTea** [comment]
That’s unfortunate. Do you have corporate security software on your device, which may be blocking requests from specific apps (like this new one)?
It’s unable to reach the Gemini API, which means that the request is getting blocked somewhere along the chain with the firewall set-up.

Local LLMs should work, though, and it may be worth giving the OpenAI API a try if you have credits there.

**Comment by myn** [comment]
Oddly enough I don't have any issues with other apps reaching out to HTTPS enabled endpoints. 

Did some googling and found this:


https://stackoverflow.com/a/55320969

https://community.netapp.com/t5/Software-Development-Kit-SDK-and-API-Discussions/Python-How-to-disable-SSL-certificate-verification/td-p/113697


```Python
import ssl
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context
```

**Comment by theJayTea** [comment]
Hi again.

Your error shows up because your corporate firewall intercepts HTTPS traffic, and likely presents a self-signed certificate which the Python ssl library does not trust — resulting in an SSL handshake failure.

Those solutions just suggest disabling HTTPS certificate verification, which would allow any certificate to be accepted; even fake ones. Doing that would make Writing Tools vulnerable to MITM attacks where an attacker could intercept the extremely sensitive traffic between it and the Gemini or other API.

## Well, I obviously can't implement this, but here's a way to potentially fix it for you. You could try installing your firewall’s root certificate:

Open a web browser and go to "https://generativelanguage.googleapis.com/$discovery/rest" (I went through the source code of the Gemini library to find this, this is what it uses).


Then click this:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/d95a3572-1493-47c7-a6fd-884e11b552d5">

And exprt the certificate crt file:

<img width="961" alt="image" src="https://github.com/user-attachments/assets/28f8bb6e-6480-49ec-a1d8-40be9515228c">


### Next, add the certificate to your system’s trusted store (I reckon you're using Windows):
	1.	Press Windows Key + R, type mmc, and press Enter.
	2.	In the MMC console, go to File > Add/Remove Snap-in.
	3.	Select Certificates and click Add. Choose Computer account and click Next > Local Computer.
	4.	Under Trusted Root Certification Authorities, right-click Certificates > All Tasks > Import.
	5.	Select the exported .crt or .pem certificate and complete the import wizard.
	6.	Restart your computer to ensure changes take effect.

This should fix it for you based on my research. Again, the issue lies with your corporate firewall, and there's nothing Writing Tools can do in itself to stop getting blocked from it. I hope this fixes it!

**Comment by myn** [comment]
Thanks so much for documenting this out.

I followed your instructions verbatim and still have the same issue.   :(
