### ISSUE TITLE
Difficulties in running the program

### ISSUE THREAD

**Issue by hanyi0914** [theJayTea/WritingTools#30]
Hello, creators. I'm experiencing some difficulties with the program on my Mac. It doesn’t seem to function the same way as demonstrated in the video; I only see a send box and cannot access the program’s features. I would appreciate your help in resolving this issue. Thank you! 
[CleanShot 2024-10-26 at 21 39 22@2x](https://github.com/user-attachments/assets/955ac9fc-f8c4-4a56-95b5-4dddffd8f071)

**Comment by momokrono** [comment]
Hi @hanyi0914 , can you give us more info? like are you running the script from the macos folder? have you setup a virtualenv?

the grid with the option won't be displayed if no text is selected, in this case I suspect cmd+c is not executed correctly. Can you copy and paste what you see in the terminal when pressing your hotkey combination?

**Comment by hanyi0914** [comment]
> Hi @hanyi0914 , can you give us more info? like are you running the script from the macos folder? have you setup a virtualenv?
> 
> the grid with the option won't be displayed if no text is selected, in this case I suspect cmd+c is not executed correctly. Can you copy and paste what you see in the terminal when pressing your hotkey combination?

Hello creators, I recorded a complete start to finish video. The process includes scripts using mac OS and scripts using window, Linux version. Please help me to check where the problem is? https://drive.google.com/file/d/1mURhXcYjyj3VmkHd1iuh7XyPdZDTvFuS/view?usp=sharing

**Comment by momokrono** [comment]
Hi @hanyi0914,
I've watched the video and there are a couple of things I'd like to point out. First, you ran both the macos version and the win_linux one, and while the latter is indeed developed and supported by us, the macos port has been developed by forking the project and creating a basic working version by a different developer.
@theJayTea included the port inside this project for those wanting to try it instead of navigating github looking for the port, but for the moment we neither support nor have ways to fix possible bugs there.

I expected the win_linux port to "work", ie spawning the windows and so on, but the copy/paste won't work since it uses ctrl+c/v while macos expects cmd+c/v.

Having said that, the documentation for the Mac port is severely lacking, for example the author of the port modified the code to convert "ctrl" to "cmd" when setting up the hotkey, but this isn't documented anywhere. In your case, you set your hotkey to be ctrl+j but the code internally changes it to cmd+j. Try and see if  with this info your hotkey works.

I am working into unifying the versions but for the moment I neither have time nor a macos pc to use for my tests.

PS: you should delete the API key you used in the video since someone can use it and rate-limit you or get you into troubles, and create a new one.

**Comment by theJayTea** [comment]
> Hello creators, I recorded a complete start to finish video. The process includes scripts using mac OS and scripts using window, Linux version. Please help me to check where the problem is?

Hey @hanyi0914, thanks for taking the time to record it and share that. I've deleted your original comment with the video link to protect your API key; it's best to delete that API key ASAP.

I'm really sorry, but I can't make any promises about the macOS version as I'm currently unable to test it myself (I broke my Hackintosh, welp!).

@kurcz may be able to resume development on it (he was able to get it working); let's see how it goes.

**Comment by hanyi0914** [comment]
> Hi @hanyi0914, I've watched the video and there are a couple of things I'd like to point out. First, you ran both the macos version and the win_linux one, and while the latter is indeed developed and supported by us, the macos port has been developed by forking the project and creating a basic working version by a different developer. @theJayTea included the port inside this project for those wanting to try it instead of navigating github looking for the port, but for the moment we neither support nor have ways to fix possible bugs there.
> 
> I expected the win_linux port to "work", ie spawning the windows and so on, but the copy/paste won't work since it uses ctrl+c/v while macos expects cmd+c/v.
> 
> Having said that, the documentation for the Mac port is severely lacking, for example the author of the port modified the code to convert "ctrl" to "cmd" when setting up the hotkey, but this isn't documented anywhere. In your case, you set your hotkey to be ctrl+j but the code internally changes it to cmd+j. Try and see if with this info your hotkey works.
> 
> I am working into unifying the versions but for the moment I neither have time nor a macos pc to use for my tests.
> 
> PS: you should delete the API key you used in the video since someone can use it and rate-limit you or get you into troubles, and create a new one.

Thanks for the heads up. I wanted to make sure that the win_linux port works fine on macOS systems (hotkey set to ctrl+j, output using cmd+j), it just causes copy/paste to not work. But the mac ported port doesn't work on top of a mac for technical reasons right?

**Comment by momokrono** [comment]
@hanyi0914 

The win_linux code doesn't copy/paste since internally triggers a ctrl+c/v, but since on mac you need to use cmd+c/v the hotkey does nothing.

The mac port _should_ work, but when you use ctrl in your hotkey it automatically translate ctrl to cmd. So if you set ctrl+j you must use cmd+j instead. @kurcz if I'm wrong, please correct me.

In any case, I'd suggest you to run the program inside a virtual environment. It's quite easy to setup.
Once you navigate inside the macos folder, just execute:
```zsh
python -m venv venv
source venv/bin/activate
```
now that you have a working virtualenv, you can
```zsh
pip install -r requirements.txt
python main.py
```

**Comment by theJayTea** [comment]
Closing this as there's now a new, native Swift macOS version maintained by @Aryamirsepasi :D
