### ISSUE TITLE
Text box disappears and nothing happens

### ISSUE THREAD

**Issue by BadBronx99** [theJayTea/WritingTools#42]
I type the prompt in or click the button and it just disappears and nothing happens.

**Comment by theJayTea** [comment]
Hello. This has been happening over the last 2 days because Google's Gemini 1.5 Flash model is down, with a "model overloaded" error:

https://discuss.ai.google.dev/t/partially-solved-gemini-models-overloading-with-token-windows-of-less-than-20/49579

I waited a day for Google to fix it, but they've still not, so I'll update Writing Tools today with a fix (switching it to use 1.5 Pro or 1.5 Flash 8B, maybe with a drop-down in settings to let you choose if the vanilla 1.5 Flash gets fixed in the future).

**Comment by BadBronx99** [comment]
When i type in a custom command it still disappears.

**Comment by BadBronx99** [comment]
I added a video here: 

Uploading Untitled video (1).mp4…

**Comment by BadBronx99** [comment]
I added a video here:
https://github.com/user-attachments/assets/798bb363-4fba-4e2e-8df3-7814a6cb3c3d

**Comment by theJayTea** [comment]
Hi @BadBronx99 , I see that you’re using macOS. Unfortunately, the macOS version is no longer being maintained. It was initially created by a contributor who got it almost working but is too busy to take it up right now. Sorry for the unfortunate news!

**Comment by BadBronx99** [comment]
I am actually on windows

**Comment by theJayTea** [comment]
@BadBronx99 i see. so i reckon you're using a macOS theme mod that comes with a rendition of Stage Manager.

That's where the issue lies. When Writing Tools is invoked, your Stage Manager thing pushes the other windows out.

Writing Tools needs to be atop the previous window for it to work and paste back your response.

Turn off your "Stage Manager" and it'll work.

**Comment by BadBronx99** [comment]
@theJayTea I turned it off (MyDockFinder) and it still did not work. This is the video:

https://github.com/user-attachments/assets/e29b0c47-9c23-4eaf-a6cd-764ae4956c5f

**Comment by BadBronx99** [comment]
Oh Ok thank you so much.
