### ISSUE TITLE
missing icon when the dmg opened on mac os 15(Writing.Tools.macOS.Beta.2 16.20.01)

### ISSUE THREAD

**Issue by WYang555** [theJayTea/WritingTools#58]
really great job. but the writingtools icon disappeared at the third time i opened the dmg. so, i do not know if the app is working while i double click the app. can you fix this bug?

**Comment by WYang555** [comment]
thus, i can not reset ai models as well

**Comment by Aryamirsepasi** [comment]
Hi, do you mean that the app is not shown in the menu bar? This icon should be there if the app is running. 
<img width="39" alt="Screenshot 2024-12-01 at 10 39 45" src="https://github.com/user-attachments/assets/e42d4d94-b2d5-47b6-914f-26d3b925dff7">

**Comment by WYang555** [comment]
yes,  i open the app, but the icon does not show, i will try the beta .3 version.
thank you for your reply

**Comment by WYang555** [comment]
i still cannot find the icon

**Comment by Aryamirsepasi** [comment]
> i still cannot find the icon

Hm, this is weird. 🤔 I'll look into it and see what I can find.

**Comment by WYang555** [comment]
i do not know if i should say this. 😭 i changed the hot key, then it disappeared in the menu bar. then, no matter what i do, it never shows.发自我的 iPhone在 2024年12月2日，04:28，Aryamirsepasi ***@***.***> 写道：﻿

i still cannot find the icon

Hm, this is weird. 🤔 I'll look into it and see what I can find.

**Comment by Aryamirsepasi** [comment]
> i do not know if i should say this. 😭 i changed the hot key, then it disappeared in the menu bar. then, no matter what i do, it never shows.发自我的 iPhone在 2024年12月2日，04:28，Aryamirsepasi ***@***.***> 写道：﻿ i still cannot find the icon Hm, this is weird. 🤔 I'll look into it and see what I can find. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Hello again, I checked the app and unfortunately couldn't find the exact cause of this. However, a new beta version will be published in the coming days that has a reset functionality which can be used. The version after that (Beta 5 or the 1.0 version will also have a recovery function to reset the app via Terminal, but that is still WIP).

There are two things that I can think of that you can try right now:

- **Running the app through the app binary:**

1. Go to your applications folder and right click on writing-tools icon
2. Select "Show Package Contents"
3. Navigate to "Contents/MacOS"
4. Double-click the app binary to launch it from Terminal (If this shows any error messages please send it to me so that I can find the problems source)

- **Deleting and installing the app again:**

1. Quit the app completely (Check Activity Monitor to make sure it is not running)
2. Either run ```defaults delete com.aryamirsepasi.writing-tools``` from Terminal (recommended) or move the app from the Applications folder to Trash and empty it
3. Restart your Device
4. Reinstall the app


Let me know if any of these fixed the problem.

**Comment by WYang555** [comment]
i tried the second method and it works
