### ISSUE TITLE
Volume down instead of catching selected text

### ISSUE THREAD

**Issue by imadraude** [theJayTea/WritingTools#7]
When I try to use Ctrl+Space, the app only lowers the volume slightly and displays a "select text first" error. I can't understand the logic behind this behavior, it happens randomly.

**Comment by theJayTea** [comment]
Hey @imadraude ! Here's how you may be able to fix it:

Run it as administrator, set the shortcut key to `ctrl+j`, and relaunch it for this to take effect.
It should then work.

On a few devices, for some reason, Writing Tools isn't properly able to intercept `ctrl+space` (maybe because of other apps in the background also registering their own similar hotkeys?), and it leads to the issue you're facing.

**Comment by theJayTea** [comment]
This may be fixed with v4. Could you please try it and let me know? Thanks

**Comment by imadraude** [comment]
Tested it for a while, works like a charm! Thanks for fixing the bug!
