### ISSUE TITLE
What is chat mode for

### ISSUE THREAD

**Issue by Raynbda** [theJayTea/WritingTools#71]
I am wondering what chat mode is useful for when there is "describe your change"

**Comment by ErrorCatDev** [comment]
@Raynbda For example, if you wanted to rephrase your sentence a certain way, you could ask WritingTools to "Make the text more friendly" or "make it more professional". Since I believe that these are already presets, you can just click the rephrase buttons, but if not you can just type them in.

**Comment by theJayTea** [comment]
hi @Raynbda ! To add onto what @ErrorCatDev said!

`Describe your change...`, as you may know, is for when you want custom changes to the selected text that's not already in the present buttons. Examples:
- Translate to French
- Make it title case
- (if you selected code) add comments
- (if you selected code) fix this code
- (if you selected code) convert to Python


---

Now the other Chat mode, which shows up as a simple prompt box when you invoke Writing Tools without selecting text, is just a super quick way to chat with an LLM (Gemini, local LLM, etc - the same one used for the other features).

You can ask it anything you would ask something like ChatGPT: generate writing such as an essay, or general knowledge questions.

In the next update, I'll make the response show in a pop-up window (instead of pasting the response to a selected textbox as it currently does).
