### ISSUE TITLE
pop-up UI features extension

### ISSUE THREAD

**Issue by sasagr** [theJayTea/WritingTools#77]
So far the pop-up UI is only available for Summarize, Key Points, and Table. Would it be possible to add also for the others, except Proofread?
I think it is always good to be able to review the output before.

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the CustomPopupWindow class to show a pop-up UI for all options except Proofread. This change allows users to review the output before applying it.

You can review changes in this commit: https://github.com/jacks-sam1010/theJayTea-WritingTools-77/commit/5f18d6cbdab9f3509a55a604961c6a0732ac7e95.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by sasagr** [comment]
this is above solution does not seem to be working

**Comment by theJayTea** [comment]
Thanks for the suggestion! You should be able to customise this in the next version :)

At least to me, I think the beauty of the concise, rewrite options etc. (and Writing Tools in general) is that it does its job in one click, without making you click around.
Right now, you can quickly compare both versions with `ctrl+z` and `ctrl+y`.

In the next version, I’ll add customisation of the buttons (rearrangement, custom buttons with their own prompts…), and I’ll make it so that you can customise whether each button replaces the text or shows it in the pop-up window.
